//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.52  Mar. 28, 2005 
// Tue Aug  9 14:08:28 2022
//
//      Input file         : D:/projekt_uec2/uec2_projekt/src/rtl/ov7670_fr/RGB.vhd
//      Design name        : RGB
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//Wersja z grayscalem
module RGB (Din, Nblank, reset, R, G, B,Grayscale);

   input[11:0] Din;
   input Nblank; 
   input reset;
   output [7:0] R ; 
   wire[7:0] R;
   output [7:0] G ; 
   wire [7:0] G;
   output [7:0] B ; 
   wire [7:0] B;
   output [7:0] Grayscale ; 
   wire [7:0] Grayscale; 

   assign R = (Nblank == 1'b1 && reset == 1'b0) ? {Din[11:8], Din[11:8]} : 8'b00000000 ;
   assign G = (Nblank == 1'b1 && reset == 1'b0) ? {Din[7:4], Din[7:4]} : 8'b00000000 ;
   assign B = (Nblank == 1'b1 && reset == 1'b0 ) ? {Din[3:0], Din[3:0]} : 8'b00000000 ;
   assign Grayscale = (Nblank == 1'b1 && reset == 1'b0 ) ? {16*(Din[11:8] + Din[7:4] + Din[3:0])/3} : 8'b00000000 ; 
    

    

endmodule
